config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
  
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    member do
      get :followings, :followers
    end
  end
  resources :talks do
    resources :responses, only: :create
  end
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :title
    validates :text
  end

  validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }

  def self.search(search)
    if search != ""
      Article.where('title LIKE(?) OR text LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Article.all
    end
  end

  def liked_by(user)
    Like.find_by(user_id: user.id, article_id: id)
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--カテゴリーを選択--' },
    { id: 2, name: 'メイク' },
    { id: 3, name: 'スキンケア' },
    { id: 4, name: 'ボディケア' },
    { id: 5, name: 'ヘアケア・スタイリング' },
    { id: 6, name: 'ネイル' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  with_options presence: true do
    validates :user_id
    validates :follower_id
  end
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :talk
  belongs_to :user

  validates :text, presence: true
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :user
  has_many :responses, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
  has_many :likes
  has_many :talks
  has_many :responses
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user
  has_one_attached :image

  validates :nickname, presence: true

  VALID_PASSWORD_REGIX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGIX }, on: :create
  validates :password, format: { with: VALID_PASSWORD_REGIX }, on: :update, allow_blank: :true

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(follower: user_id)
  end

  def unfollow(relationship_id)
    relationships.find(relationship_id).destroy!
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @articles = Article.includes(:user).order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def edit
  end

  def update
    @article.update(article_params)
    if @article.save
      redirect_to article_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def search
    @articles = Article.search(params[:keyword]).order('created_at DESC')
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category_id, images: []).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @article.user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to article_path(@comment.article)
    else
      @article = @comment.article
      @comments = @article.comments
      render "articles/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @like = current_user.likes.build(like_params)
    @article = @like.article
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @article = @like.article
    if @like.destroy
      respond_to :js
    end
  end

  private
  
  def like_params
    params.permit(:article_id)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_talk, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @talks = Talk.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.valid?
      @talk.save
      redirect_to talks_path
    else
      render :new
    end
  end

  def show
    @response = Response.new
    @responses = @talk.responses.includes(:user)
  end

  def edit
  end

  def update
    @talk.update(talk_params)
    if @talk.save
      redirect_to talk_path
    else
      render :edit
    end
  end

  def destroy
    @talk.destroy
    redirect_to talks_path
  end

  private

  def talk_params
    params.require(:talk).permit(:title, :text, :image).merge(user_id: current_user.id)
  end

  def set_talk
    @talk = Talk.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @talk.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:followings, :followers]
  def show
    @user = User.find(params[:id])
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%# いいね機能 %>
<% if user_signed_in? %>
  <% if @article.liked_by(current_user).present? %>
    <%= link_to article_like_path(@article.id, @article.liked_by(current_user)), method: :delete, remote: true, class: "like-link" do %>
      <i class="fa fa-heart unlike-btn", id="unlike"></i>
    <% end %>
    <%= @article.likes.count %>
  <% else %>
    <%= link_to article_likes_path(@article), method: :post, remote: true, class: "like-link" do %>
      <i class="fa fa-heart like-btn", id="like"></i>
    <% end %>
    <%= @article.likes.count %>
  <% end %>
<% else %>
  <i class="fa fa-heart like-btn"></i>
  <%= @article.likes.count %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <div class="form">
    <div class="form-area">
      <h2 class="title">記事の編集</h2>
      <%= render partial: 'layouts/form', locals: { article: @article } %>
    </div>
  </div>
</div>

<% breadcrumb :edit_article, @article %>

app/views/articles/index.html.erb
<div class="title-bg">
  <div class="title-contents">
    <h1 class="service-title">niceCOSME</h1>
    <h2 class="service-text">
    niceCOSMEは美容の情報交換ができるアプリです
    </h2>
  </div>
</div>

<div class="article-index">
  <%# 記事一覧 %>
  <h2 class="title">新着記事</h2>
  <div class="article-contents">
    <% @articles.each do |article| %>
      <%= render partial: "layouts/article", locals: { article: article } %>
    <% end %>
  </div>

  <div class="fixed-btn">
    <%= link_to new_article_path do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
  </div>
  <%# /記事一覧 %>
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="form">
    <div class="form-area">
      <h2 class="form-title">新規投稿</h2>
      <%= render partial: 'layouts/form', locals: { article: @article } %>
    </div>
  </div>
</div>

<% breadcrumb :new_article %>

app/views/articles/search.html.erb
<div class="container">
  <div class="article-contents">
    <% @articles.each do |article| %>
      <%= render partial: "layouts/article", locals: { article: article } %>
    <% end %>
  </div>

  <div class="fixed-btn">
    <%= link_to new_article_path do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
  </div>
</div>

<% breadcrumb :search_article %>

app/views/articles/show.html.erb
<div class="container">

  <%# 記事詳細表示 %>
  <div class="article-show-contents">
    <div class="article-show-mdl-contents">
      <div class="article-title">
        <h2><%= @article.title %></h2>
      </div>

      <div class="article-show-image">
        <div class="slider">
          <% if @article.images.present? %>
            <% @article.images.each do |image| %>
              <%= image_tag image, class: "article-show-img" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="post-user-menu">
        <%= link_to user_path(@article.user) do %>
          <div class="post-show-name">
            <% if @article.user.image.present? %>
              <%= image_tag @article.user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= @article.user.nickname %>
          </div>
        <% end %>

        <div class="dropdown-menu">
          <% if user_signed_in? && current_user.id == @article.user_id %>
            <ul class="dropdown" id="dropdown">
              <li><i class="fas fa-ellipsis-h"></i></li>
            </ul>
            <ul class="dropdown-list hidden" id="dropdown-list">
              <li><%= link_to "編集", edit_article_path(@article.id) %></li>
              <li><%= link_to "削除", article_path(@article.id), method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>

      <div class="article-show-text">
        <%= simple_format(@article.text) %>
      </div>
      <div class="article-show-date">
        <%= l @article.created_at, format: :short %>
      </div>
      <div class="article-category">
        <%= link_to "カテゴリー：#{@article.category.name}", category_path(@article.category) %>
      </div>

      <div class="favorite" id="article_<%= @article.id %>">
        <%= render 'articles/article', article: @article %>
      </div>
    </div>
  </div>
  <%# /記事詳細表示 %>

  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with(model: [@article, @comment], local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="field">
          <%= f.text_area :text, placeholder: "コメントする", class: "form-long-text" %>
        </div>
        <div class="send">
          <%= f.submit "コメント", class: "send-btn" %>
        </div>
      <% end %>
    <% else %>
      <strong><p>***コメントの投稿には新規登録/ログインが必要です***</p></strong>
    <% end %>
  </div>

  <h2 class="title">コメント一覧</h2>

  <div class="comment-lists">
    <div class="comment-list">
    <% @comments.each do |comment| %>
      <div class="comment-mdl-list">
        <%= link_to user_path(comment.user) do %>
          <div class="post-show-name">
            <% if comment.user.image.present? %>
              <%= image_tag comment.user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= comment.user.nickname %>
          </div>
        <% end %>

        <div class="comment-text">
          <%= simple_format(comment.text) %>
        </div>
        <div class="comment-date">
          <%= l comment.created_at, format: :short %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<% breadcrumb :show_article, @article %>

app/views/likes/create.js.erb
document.getElementById('article_<%= @article.id %>').innerHTML = '<%= j(render @article) %>'

app/views/likes/destroy.js.erb
document.getElementById('article_<%= @article.id %>').innerHTML = '<%= j(render @article) %>'

app/views/talks/_form.html.erb
<%= form_with(model: @talk, local: true) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, placeholder:"タイトル", class: "form-title-text" %>
  </div>

  <div class="field">
    <%= f.label :text, "本文" %><br />
    <%= f.text_area :text, placeholder:"本文", class: "form-long-text" %>
  </div>

  <div class="send">
    <%= f.submit "投稿する", class: "send-btn" %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<div class="container">
  <div class="form">
    <div class="form-area">
      <h2 class="form-title">投稿の編集</h2>
      <%= render partial: 'form', locals: { talk: @talk } %>
    </div>
  </div>
</div>

<% breadcrumb :edit_talk, @talk %>

app/views/talks/index.html.erb
<div class="container">
  <h2 class="title">Q＆A</h2>
  <div class="talk-contents">
    <p>質問やお悩み相談ができるスペースです。</p>
    <div class="q-jump">
      <%= link_to "質問・相談する", new_talk_path, class: "q-btn" %>
    </div>
  </div>

  <h2 class="title">質問一覧</h2>
  
  <%# Q＆A一覧 %>
  <div class="talk-lists">
    <div class="talk-list">
    <% @talks.each do |talk| %>
      <div class="talk-mdl-list">
        <%= link_to talk_path(talk.id) do %>
          <h3 class="talk-title">
            <%= talk.title %>
          </h3>
          <div class="talk-text">
            <%= talk.text.truncate(50) %>
          </div>
          <div class="talk-bottom">
            <div class="user-name">
              <% if talk.user.image.present? %>
                <%= image_tag talk.user.image, class: "user-icon" %>
              <% else %>
                <%= image_tag "noimage-user.png", class: "user-icon" %>
              <% end %>
              <%= talk.user.nickname %>
            </div>
            <div class="talk-date">
              <%= l talk.created_at, format: :short %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
  <%# /Q＆A一覧 %>
  
  <%= paginate @talks %>
</div>

<% breadcrumb :talks %>

app/views/talks/new.html.erb
<div class="container">
  <div class="form">
    <div class="form-area">
      <h2 class="form-title">新規投稿</h2>
      <%= render partial: 'form', locals: { talk: @talk } %>
    </div>
  </div>
</div>

<% breadcrumb :new_talk %>

app/views/talks/show.html.erb
<div class="container">

  <%# Q＆A詳細表示 %>
  <div class="talk-thread">
    <div class="talk-show-contents">
      <div class="talk-show-title">
        <h2><%= @talk.title %></h2>
      </div>

      <div class="post-user-menu">
        <%= link_to user_path(@talk.user) do %>
          <div class="post-show-name">
            <% if @talk.user.image.present? %>
              <%= image_tag @talk.user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= @talk.user.nickname %>
          </div>
        <% end %>

        <div class="dropdown-menu">
          <% if user_signed_in? && current_user.id == @talk.user_id %>
            <ul class="dropdown" id="dropdown">
              <li><i class="fas fa-ellipsis-h"></i></li>
            </ul>
            <ul class="dropdown-list hidden" id="dropdown-list">
              <li><%= link_to "編集", edit_talk_path(@talk.id) %></li>
              <li><%= link_to "削除", talk_path(@talk.id), method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>

      <div class="talk-show-text">
        <%= simple_format(@talk.text) %>
      </div>
      <div class="talk-show-date">
        <%= l @talk.created_at, format: :short %>
      </div>
    </div>
  </div>
  <%# /Q＆A詳細表示 %>

  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with(model: [@talk, @response], local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="field">
          <%= f.text_area :text, placeholder: "回答を入力", class: "form-long-text" %>
        </div>
        <div class="send">
          <%= f.submit "回答する", class: "send-btn" %>
        </div>
      <% end %>
    <% else %>
      <strong><p>***回答には新規登録/ログインが必要です***</p></strong>
    <% end %>
  </div>

  <h2 class="title">回答一覧</h2>

  <div class="comment-lists">
    <div class="comment-list">
    <% @responses.each do |response| %>
      <div class="comment-mdl-list">
        <%= link_to user_path(response.user) do %>
          <div class="post-show-name">
            <% if response.user.image.present? %>
              <%= image_tag response.user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= response.user.nickname %>
          </div>
        <% end %>

        <div class="comment-text">
          <%= simple_format(response.text) %>
        </div>
        <div class="comment-date">
          <%= l response.created_at, format: :short %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<% breadcrumb :show_talk, @talk %>

app/views/users/followers.html.erb
<div class="container">
  <div class="follow">
    <div class="follow-list">
      <h2 class="title">フォロワ一覧</h2>
      <% @users.each do |user| %>
        <%= link_to user_path(user.id) do %>
          <div class="user-name">
            <% if user.image.present? %>
              <%= image_tag user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= user.nickname %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% breadcrumb :follower, @user %>

app/views/users/followings.html.erb
<div class="container">
  <div class="follow">
    <div class="follow-list">
      <h2 class="title">フォロー一覧</h2>
      <% @users.each do |user| %>
        <%= link_to user_path(user.id) do %>
          <div class="user-name">
            <% if user.image.present? %>
              <%= image_tag user.image, class: "user-icon" %>
            <% else %>
              <%= image_tag "noimage-user.png", class: "user-icon" %>
            <% end %>
            <%= user.nickname %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% breadcrumb :following, @user %>

app/views/users/show.html.erb
<div class="container">
  <div class="profile">
    <h2 class="title"><%= @user.nickname %>さん</h2>
    <div class="user-info">
      <% if @user.image.present? %>
        <%= image_tag @user.image, class: "user-image" %>
      <% else %>
        <%= image_tag "noimage-user.png", class: "user-image" %>
      <% end %>
    </div>

    <%# フォロー機能 %>
    <div id="relationship_<%= @user.id %>">
      <%= render partial: "relationships/relationship", locals: { user: @user } %>
    </div>
    <%# /フォロー機能 %>
  </div>

  <ul class="tab">
    <li><%= link_to "記事", "#user-article" %></li>
    <li><%= link_to "いいね", "#user-like" %></li>
  </ul>

  <%# 投稿記事一覧 %>
  <div id="user-article" class="area is-active">
    <h2 class="title"><%= @user.nickname %>さんの記事一覧</h2>
    <div class="article-contents">
      <% @user.articles.reverse_each do |article| %>
        <%= render partial: "layouts/article", locals: { article: article } %>
      <% end %>
    </div>
  </div>
  <%#/ 投稿記事一覧 %>

  <%# いいねした記事一覧 %>
  <div id="user-like" class="area">
    <h2 class="title"><%= @user.nickname %>さんのいいねした記事一覧</h2>
    <div class="article-contents">
      <% @user.likes.reverse_each do |like| %>
        <div class="article-list">
          <%= link_to article_path(like.article.id) do %>
          <div class="article-mdl-list">
            <div class="article-image">
              <% if like.article.images.present? %>
                <% like.article.images.first(1).each do |image| %>
                  <%= image_tag image, class: "article-img" %>
                <% end %>
              <% else %>
                <%= image_tag "noimage.jpg", class: "article-img" %>
              <% end %>
            </div>

            <div class="article-info">
              <h3 class="article-title">
                <%= like.article.title.truncate(16) %>
              </h3>
              <div class="article-text">
                <%= like.article.text.truncate(19) %>
              </div>
              <div class="article-bottom">
                <div class="user-name">
                  <% if like.article.user.image.present? %>
                    <%= image_tag like.article.user.image, class: "user-icon" %>
                  <% else %>
                    <%= image_tag "noimage-user.png", class: "user-icon" %>
                  <% end %>
                  <%= like.article.user.nickname %>
                </div>
                <div class="article-like">
                  <i class="fa fa-heart like-btn"></i>
                  <%= like.article.likes.count %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>    
      <% end %>
    </div>
  </div>
  <%# /いいねした記事一覧 %>
</div>

<% breadcrumb :show_user, @user %>