config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
  
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    member do
      get :followings, :followers
    end
  end
  resources :talks do
    resources :responses, only: :create
  end
  resources :categories, only: :show
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :title
    validates :text
  end

  validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }

  def self.search(search)
    if search != ""
      Article.where('title LIKE(?) OR text LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Article.all
    end
  end

  def liked_by(user)
    Like.find_by(user_id: user.id, article_id: id)
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--カテゴリーを選択--' },
    { id: 2, name: 'メイク' },
    { id: 3, name: 'スキンケア' },
    { id: 4, name: 'ボディケア' },
    { id: 5, name: 'ヘアケア・スタイリング' },
    { id: 6, name: 'ネイル' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  with_options presence: true do
    validates :user_id
    validates :follower_id
  end
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :talk
  belongs_to :user

  validates :text, presence: true
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :user
  has_many :responses, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
  has_many :likes
  has_many :talks
  has_many :responses
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user
  has_one_attached :image

  validates :nickname, presence: true

  VALID_PASSWORD_REGIX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGIX }, on: :create
  validates :password, format: { with: VALID_PASSWORD_REGIX }, on: :update, allow_blank: :true

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(follower: user_id)
  end

  def unfollow(relationship_id)
    relationships.find(relationship_id).destroy!
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @like = current_user.likes.build(like_params)
    @article = @like.article
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @article = @like.article
    if @like.destroy
      respond_to :js
    end
  end

  private
  
  def like_params
    params.permit(:article_id)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_talk, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @talks = Talk.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.valid?
      @talk.save
      redirect_to talks_path
    else
      render :new
    end
  end

  def show
    @response = Response.new
    @responses = @talk.responses.includes(:user)
  end

  def edit
  end

  def update
    @talk.update(talk_params)
    if @talk.save
      redirect_to talk_path
    else
      render :edit
    end
  end

  def destroy
    @talk.destroy
    redirect_to talks_path
  end

  private

  def talk_params
    params.require(:talk).permit(:title, :text, :image).merge(user_id: current_user.id)
  end

  def set_talk
    @talk = Talk.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @talk.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:followings, :followers]
  def show
    @user = User.find(params[:id])
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_article.html.erb
<%# 記事一覧 %>
<div class="article-list">
  <%= link_to article_path(article.id) do %>
  <div class="article-mdl-list">
    <div class="article-image">
    <% if article.images.present? %>
      <% article.images.first(1).each do |image| %>
        <%= image_tag image, class: "article-img" %>
      <% end %>
    <% else %>
      <%= image_tag "noimage.jpg", class: "article-img" %>
    <% end %>
    </div>
  
    <div class="article-info">
      <h3 class="article-title">
        <%= article.title.truncate(16) %>
      </h3>
      <div class="article-text">
        <%= article.text.truncate(19) %>
      </div>
      <div class="article-bottom">
        <div class="user-name">
          <% if article.user.image.present? %>
            <%= image_tag article.user.image, class: "user-icon" %>
          <% else %>
            <%= image_tag "noimage-user.png", class: "user-icon" %>
          <% end %>
          <%= article.user.nickname %>
        </div>
        <div class="article-like">
          <i class="fa fa-heart like-btn"></i>
          <%= article.likes.count %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, placeholder:"タイトル", class: "form-title-text" %>
  </div>

  <div class="field">
    <%= f.label :text, "本文" %><br />
    <%= f.text_area :text, placeholder:"本文", class: "form-long-text" %>
  </div>

  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"pulldown"}) %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :images, name: 'article[images][]', id: 'article_image' %>
    <div id="image-list"></div>
  </div>

  <% @article.images.each do |image| %>
    <%= image_tag image, class: 'images' %>
  <% end %>

  <div class="send">
    <%= f.submit "投稿する", class: "send-btn" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>niceCOSME</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <div id="wrapper">
      <header class="header">
        <div class="top-header">
          <div class="nav_left">
            <div class="logo-space">
              <%= link_to image_tag("logo.jpg", class: :logo), root_path %>
            </div>

            <div class="search-form">
              <%= form_with(url: search_articles_path, local: true, method: :get) do |f| %>
                <%= f.text_field :keyword, placeholder: "検索", class: "search-form-field" %>
                <%= button_tag type: "submit", class: "search-btn" do %>
                  <i class="fas fa-search-plus"></i>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="nav_right">
            <div class="login-status">
              <%# ログイン状態 %>
              <% if user_signed_in? %>
                <div class="user-name" id="login-menus">
                  <% if current_user.image.present? %>
                    <%= image_tag current_user.image, class: "user-icon" %>
                  <% else %>
                    <%= image_tag "noimage-user.png", class: "user-icon" %>
                  <% end %>
                  <div class="login-name">
                    <%= current_user.nickname %>
                  </div>
                  <i class="fas fa-chevron-down"></i>
                </div>

                <ul class="login-menu hidden" id="login-menu">
                  <li><%= link_to "マイページ", user_path(current_user) %></li>
                  <li><%= link_to "登録情報の編集", edit_user_registration_path(current_user.id) %></li>
                  <li><span><%= link_to "ログアウト", destroy_user_session_path, method: :DELETE %></span></li>
                </ul>
              <%# ログアウト状態 %>
              <% else %>
                <%= link_to "新規登録", new_user_registration_path %>　
                <%= link_to "ログイン", new_user_session_path %>
              <% end %>
            </div>

            <div class="post-btn">
              <%= link_to "記事を投稿する", new_article_path %>
            </div>

            <%# スマホ表示 %>
            <div class="mobile-menu">
              <div class="btn-menu"><i class="fa fa-bars" id="open"></i></div>
              <ul class="main-nav" id="main-nav">
                <div class="mobile-search-form">
                  <%= form_with(url: search_articles_path, local: true, method: :get) do |f| %>
                    <%= f.text_field :keyword, placeholder: "検索", class: "search-form-field" %>
                    <%= button_tag type: "submit", class: "search-btn" do %>
                      <i class="fas fa-search-plus"></i>
                    <% end %>
                  <% end %>
                </div>

                <li><%= link_to "TOP", root_path %></li>

                <%# ログイン状態 %>
                <% if user_signed_in? %>
                  <li><%= link_to "マイページ", user_path(current_user) %></li>
                  <li><%= link_to "登録情報の編集", edit_user_registration_path(current_user.id) %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :DELETE %></li>
                <%# ログアウト状態 %>
                <% else %>
                  <li><%= link_to "新規登録", new_user_registration_path %></li>
                  <li><%= link_to "ログイン", new_user_session_path %></li>
                <% end %>

                <ul class="accordion-area">
                  <li class="accordion">カテゴリー</li>
                  <ul class="box">
                    <li><%= link_to "メイク", "/categories/2" %></li>
                    <li><%= link_to "スキンケア", "/categories/3" %></li>
                    <li><%= link_to "ボディケア", "/categories/4" %></li>
                    <li><%= link_to "ヘアケア・スタイリング", "/categories/5" %></li>
                    <li><%= link_to "ネイル", "/categories/6" %></li>
                    <li><%= link_to "その他", "/categories/7" %></li>
                  </ul>
                </ul>

                <li><%= link_to "Q＆A", talks_path %></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="bottom-header">
          <ul class="nav_links">
            <li id="lists">カテゴリー</li>
            <li class="q-link"><%= link_to "Q＆A", talks_path %></li>
          </ul>
          <ul class="category-lists hidden" id="pull-down">
            <li><%= link_to "メイク", "/categories/2" %></li>
            <li><%= link_to "スキンケア", "/categories/3" %></li>
            <li><%= link_to "ボディケア", "/categories/4" %></li>
            <li><%= link_to "ヘアケア・スタイリング", "/categories/5" %></li>
            <li><%= link_to "ネイル", "/categories/6" %></li>
            <li><%= link_to "その他", "/categories/7" %></li>
          </ul>
        </div>

      </header>

      <%= breadcrumbs separator: " &rsaquo; ", class: "breadcrumb" %>
      <%= yield %>
      <footer class="footer">
        <p class="copyright">©︎ 2021 niceCOSME</p>
      </footer>
    </div>
  </body>
</html>